version: "3"
services:
    multiply:
        container_name: multiply-service
        restart: unless-stopped
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - .:/app_multiply:delegated