version: '3'
services:
    even-service:
        extends: 
            file: ./even-generator/docker-compose.yaml
            service: even
    
    odd-service:
        extends: 
            file: ./odd-generator/docker-compose.yaml
            service: odd
    rabbit:
        image: "rabbitmq:3-management"
        environment: 
            RABBITMQ_ERLANG_COOKIE: "SGJHDLDSAHJFSAKJFSALKHS"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
