version: '3'
services:
    even-service:
        extends: 
            file: ./even-generator/docker-compose.yaml
            service: even
    
    odd-service:
        extends: 
            file: ./odd-generator/docker-compose.yaml
            service: odd
    rabbit:
        image: "rabbitmq:3-management"
        environment: 
            RABBITMQ_ERLANG_COOKIE: "SGJHDLDSAHJFSAKJFSALKHS"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
    multiply-service:
        depends_on: 
            - "rabbit"
        extends: 
            file: ./multiply-publisher/docker-compose.yaml
            service: multiply

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_admin
            MONGO_INITDB_ROOT_PASSWORD: mongo_passwd
            MONGO_INITDB_DATABASE: byne
        
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_passwd
    
    multiply-api:
        depends_on: 
            - "mongo"
            - "rabbit"
        extends: 
            file: ./multiply-api/docker-compose.yaml
            service: multiply-api
    client-vue:
        depends_on: 
            - "multiply-api"
        extends: 
            file: ./client/docker-compose.yaml
            service: client-vue