version: "3"
services:
    multiply-api:
        container_name: multiply-api
        restart: unless-stopped
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes: 
            - .:/multiply_api:delegated