version: '3'
services:
    even:
        container_name: even-service
        restart: unless-stopped
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        volumes: 
            - .:/app:delegated